### ISSUE TITLE
Canais do Youtube QA

### ISSUE THREAD

**Issue by lucascronemberger** [qajonatasmartins/qa.teste-de-software.MARKDOWN#10]
Avalie a inclusão desse canais em **Canais do Youtube QA**

1 - Andre Okazaki
https://www.youtube.com/@OkazakiAndre

2 - Priscila Caimi
https://www.youtube.com/@priscilacaimi

3 - Letícia Moreira
https://www.youtube.com/@lelemainechannel

4 - Vinicius Pessoni 
https://www.youtube.com/@pessonizando

5 - Marcos Dósea
https://www.youtube.com/@MarcosDosea

6 - ChronosAcademy
https://www.youtube.com/@ChronosAcademyBR

7 - Silvio Aulik
https://www.youtube.com/@silvioaulik4300

8 - Tester Code
https://www.youtube.com/@testercode

9 - QaOps
https://www.youtube.com/@QaOps

10 - Café Testes e Pão de Queijo
https://www.youtube.com/@cafetestesepaodequeijo1860

11 - Embaixadora da Qualidade
https://www.youtube.com/@embaixadoradaqualidade7044

12 - Assert+
https://www.youtube.com/@AssertPlus

13 - Rodrigo Matola Testando Suave
https://www.youtube.com/@testandosuave

14 - Pedro - QA Analista
https://www.youtube.com/@pedro-qaanalista69

15 - QA ACTION
https://www.youtube.com/@qaaction8512

**Comment by qajonatasmartins** [comment]
Adicionado
