### ISSUE TITLE
Adicionar "xdecision" em "qa.teste-de-software.MARKDOWN > sites para QA > sitesQA.md > Tools"

### ISSUE THREAD

**Issue by AndressaKarla** [qajonatasmartins/qa.teste-de-software.MARKDOWN#11]
Se possível, vc poderia adicionar "xdecision" em "qa.teste-de-software.MARKDOWN > sites para QA > sitesQA.md > Tools"?
- [xdecision](http://juliodelima.com.br/xdecision/pt) -> ferramenta gratuita do Júlio de Lima, usada para projetar casos de teste por meio de criação de tabelas de decisão com base em requisitos. Nesse vídeo é explicado como usar essa ferramenta na prática https://www.youtube.com/watch?v=3wtavNon34A

**Comment by qajonatasmartins** [comment]
Site do xdecision adicionado na seção de tools de sites para QAs
