### ISSUE TITLE
Adicionar algumas trilhas/roadmaps QA em "qa.teste-de-software.MARKDOWN > README.md > Trilha de carreira" OU em "qa.teste-de-software.MARKDOWN > mindmaps"

### ISSUE THREAD

**Issue by AndressaKarla** [qajonatasmartins/qa.teste-de-software.MARKDOWN#12]
Se possível, vc poderia adicionar essas trilhas/roadmaps QA em "qa.teste-de-software.MARKDOWN > README.md > Trilha de carreira" OU em "qa.teste-de-software.MARKDOWN > mindmaps" ?
- "VV - Roadmap QA Engineer": https://miro.com/app/board/o9J_lQrhQMQ=/
- "Jornada do QA": https://miro.com/app/board/uXjVOPexQIA=/?moveToWidget=3458764522554436125&cot=14
- "Mapa de Levels de Test Engineer": https://medium.com/stonetech/mapa-de-levels-de-test-engineer-da9c46ff59b7
- "QARoadMap": https://miro.com/app/board/o9J_kkqqHXk=/

**Comment by qajonatasmartins** [comment]
Por favor, add os 3 ultimos.

O "VV - Roadmap QA Engineer" precisa ser revisto, possui muitos itens na bolinha errada ou que não tem relação com QA, alguns são itens que precisa estar numa parte de desenvolvedor mas que o QA precisa ter a compreensão somente.
