### ISSUE TITLE
Novas sugestões de referencias QA

### ISSUE THREAD

**Issue by santosvini** [qajonatasmartins/qa.teste-de-software.MARKDOWN#14]
Algumas referências para serem adicionadas ao repositório:

William Alves Da Silva - QA.Coders
- [Instagram](https://www.instagram.com/qa.coders/)
- [Linkedin](https://www.linkedin.com/in/william-alves-da-silva-5b777924/)
- [Linkedin](https://www.linkedin.com/company/qa-coders/)
- [Youtube](https://www.youtube.com/channel/UCtz9rV2Ieq5-RF4VcZ4bOkA)
- [Github](https://github.com/Qa-Coders)

Priscila Caimi
- [Instagram](https://www.instagram.com/priscila.caimi/?hl=pt-br)
- [Linktree](https://linktr.ee/priscilacaimi)
- [Github](https://github.com/paraujocaimi)
- [Linkedin](https://www.linkedin.com/in/paraujocaimi/)

Renata Andrade
- [Site](https://testingwithrenata.com/)
- [Instagram](https://www.instagram.com/testingwithrenata/?hl=pt-br)
- [Keepo](https://keepo.io/testingwithrenata/)
- [Github](https://github.com/raptatinha)
- [Linkedin](https://www.linkedin.com/in/raptatinha/)
- [Youtube](https://www.youtube.com/@testingwithrenata)

Conie Menezes
- [Instagram](https://www.instagram.com/conie.menezes/)
- [Instagram](https://www.instagram.com/girls.testing/)
- [Site](https://www.coniemenezes.com/)
- [Github](https://github.com/users/coniemenezes)
- [Linkedin](https://www.linkedin.com/in/coniemenezes/)
- [Youtube](https://www.youtube.com/c/ConieMenezesBr)

**Comment by qajonatasmartins** [comment]
Indicações aceitas e adicionadas nas referencias
