### ISSUE TITLE
Frameworks/Ferramentas

### ISSUE THREAD

**Issue by santosvini** [qajonatasmartins/qa.teste-de-software.MARKDOWN#15]
# Frameworks/Ferramentas

## Mobile
- [Appium](https://appium.io/docs/en/2.0/)
- [CodeceptJS](https://codecept.io/mobile/)
- [Detox](https://codecept.io/detox/)

## Web
- [CodeceptJS](https://codecept.io/quickstart/)
- [Pupeteer](https://pptr.dev/)
- [TestCafe](https://testcafe.io/)

## API
- [CodeceptJS](https://codecept.io/api/)
- [Pupeteer](https://pptr.dev/api/puppeteer.puppeteernode)
- [TestCafe](https://testcafe.io/documentation/402632/api)

## Desktop
- [Robotframework](https://robotframework.org/)
Verificar em resources as libs disponíveis p/ automação desktop

**Comment by qajonatasmartins** [comment]
Algumas das sugestões foram aceitas e adicionadas no reporistorio
