### ISSUE TITLE
Sugestão de pasta "Canais Youtube"

### ISSUE THREAD

**Issue by santosvini** [qajonatasmartins/qa.teste-de-software.MARKDOWN#2]
Boa Noite,

Segue sugestões de canais para incluir no repo

- [TAT](https://www.youtube.com/talkingabouttesting)
- [QAzando](https://www.youtube.com/@QAzando)
- [Cypress](https://www.youtube.com/channel/UC-EOsTo2l2x39e4JmSaWNRQ)
- [Agilizei](https://www.youtube.com/channel/UCI_m5uwJjfD7trqcwAB8E3w)
- [Julio de Lima](https://www.youtube.com/@JuliodeLimas)

**Comment by qajonatasmartins** [comment]
Seção add no readme.md do projeto.

Obrigado pela contribuição ❤️
