### ISSUE TITLE
Pasta Frameworks

### ISSUE THREAD

**Issue by santosvini** [qajonatasmartins/qa.teste-de-software.MARKDOWN#3]
Adicionar em Frameworks/Ferramentas

Em Web:
- [Robot Framework](https://robotframework.org/)

Em API:
- [Robot Framework](https://robotframework.org/)
- [Postman](https://www.postman.com/product/tools/)

**Comment by qajonatasmartins** [comment]
Obrigado por contribuir com o projeto 🫶🏻
