### ISSUE TITLE
Sugestão de "Sites para QA"

### ISSUE THREAD

**Issue by santosvini** [qajonatasmartins/qa.teste-de-software.MARKDOWN#4]
Segue sugestões de sites para add ao repositório:

Sites:
- [Tips](https://cypress.tips/)

Newsletter:
- [TAT](https://mailchi.mp/6b1f35857228/newsletter-talking-about-testing)

Blog: 
- [TAT](https://talkingabouttesting.com/)
- [Medium](https://medium.com/@mayfernandes)

Cursos Free:
- [QAcademy](https://app.qacademy.io/)
- [Formação Quality Assurance (QA) Experience](https://web.dio.me/track/gft-quality-assurance-1)
- [GFT Quality Assurance Para Mulheres](https://web.dio.me/track/gft-quality-assurance-para-mulheres)
- [ISolution](https://isolution.pro/pt/t)

**Comment by qajonatasmartins** [comment]
Obrigado por compartilhar com o projeto
