### ISSUE TITLE
Sugestões para "Refêrencias de Qualidade de Software"

### ISSUE THREAD

**Issue by santosvini** [qajonatasmartins/qa.teste-de-software.MARKDOWN#5]
Algumas referências que possam ser adicionadas ao repositório:

Mayara Ribeiro Fernandes
- [Github](https://github.com/mayribeirofernandes)
- [Linkedin](https://www.linkedin.com/in/mayfernandes/)

Walmyr Lima e Silva Filho
- [Github](https://github.com/wlsf82)
- [Linkedin](https://www.linkedin.com/in/walmyr-lima-e-silva-filho/)
- [Youtube](https://www.youtube.com/@TalkingAboutTesting)
- [Twitter](https://twitter.com/walmyrlimaesilv)

Paulo Gonçalves
- [Github](https://github.com/PauloGoncalvesBH)
- [Linkedin](https://www.linkedin.com/in/paulo-goncalves/)

Gleb Bahmutov
- [Github](https://github.com/bahmutov)
- [Linkedin](https://www.linkedin.com/in/bahmutov/)
- [Site](https://glebbahmutov.com/)
- [Twitter](https://twitter.com/bahmutov)

**Comment by qajonatasmartins** [comment]
Obrigado por contribuir com o projeto
