### ISSUE TITLE
Sugestão de criação da pasta "Repositórios Úteis"

### ISSUE THREAD

**Issue by santosvini** [qajonatasmartins/qa.teste-de-software.MARKDOWN#6]
Segue sugestão de link de repo(s) para QA's

Repositório
- [QA Brasil](https://github.com/qa-brasil)
- [QA Wolf](https://github.com/qawolf/qawolf)

**Comment by qajonatasmartins** [comment]
Obrigado por contribuir com o projeto para os QAs 🫶🏻
